import React from 'react';
import { Button, Container } from '@mui/material';
import { Link } from 'react-router-dom';

const Tags = () => {
  const Technologies: string[] = [
    'React',
    'Node',
    'Express',
    'MongoDB',
    'Firebase',
    'Angular',
    'Vue',
    'Svelte',
    'TypeScript',
    'JavaScript',
    'HTML',
    'CSS',
    'Sass',
    'Less',
    'Webpack',
    'Babel',
    'Gulp',
    'Grunt',
    'Jest',
    'Mocha',
    'Chai',
    'Cypress',
    'Jasmine',
    'Karma',
    'Protractor',
    'Storybook',
    'Next.js',
    'Nuxt.js',
    'Gatsby',
    'GraphQL',
    'Apollo',
    'Redux',
    'MobX',
    'RxJS',
    'D3.js',
    'Three.js',
    'Chart.js',
    'Lodash',
    'Moment.js',
    'Immutable.js',
    'Styled-Components',
    'Emotion',
    'Tailwind CSS',
    'Bootstrap',
    'Foundation',
    'Bulma',
    'Material-UI',
    'Ant Design',
    'PrimeReact',
    'Semantic UI',
    'SvelteKit',
    'Blitz.js',
    'Remix',
    'Solid.js',
    'Qwik',
    'Tauri',
    'Electron',
    'Capacitor',
    'Ionic',
    'NativeScript',
    'Expo',
    'React Native',
    'Flutter',
    'Swift',
    'Kotlin',
    'Objective-C',
    'Java',
    'Spring Boot',
    'Hibernate',
    'Micronaut',
    'Quarkus',
    'Vert.x',
    'Ktor',
    'ASP.NET',
    'Blazor',
    'Django',
    'Flask',
    'FastAPI',
    'Ruby on Rails',
    'Sinatra',
    'Hanami',
    'Phoenix',
    'Elixir',
    'Laravel',
    'Symfony',
    'CodeIgniter',
    'CakePHP',
    'Zend Framework',
    'Yii',
    'FuelPHP',
    'Phalcon',
    'Slim',
    'Virto Commerce',
    'nopCommerce',
    'X-Cart',
    'CS-Cart',
    'osCommerce',
    'Zen Cart',
    'CubeCart',
    'AbanteCart',
    'LiteCart',
    'TomatoCart',
    'OpenCart',
    'PrestaShop',
    'WooCommerce',
    'Shopware',
    'OroCommerce',
    'Broadleaf Commerce',
    'Virto Commerce',
    'nopCommerce',
    'X-Cart',
    'CS-Cart',
    'osCommerce',
    'Zen Cart',
    'CubeCart',
    'AbanteCart',
    'LiteCart',
    'TomatoCart',
    'OpenCart',
    'PrestaShop',
    'WooCommerce',
    'Shopware',
    'OroCommerce',
    'Broadleaf Commerce',
    'Virto Commerce',
    'nopCommerce',
    'X-Cart',
    'CS-Cart',
    'osCommerce',
    'Zen Cart',
    'CubeCart',
    'AbanteCart',
    'LiteCart',
    'TomatoCart',
    'OpenCart',
    'PrestaShop',
    'WooCommerce',
    'Shopware',
    'OroCommerce',
    'Broadleaf Commerce',
    'Virto Commerce',
    'nopCommerce',
    'OroCommerce',
    'Broadleaf Commerce',
    'Virto Commerce',
    'nopCommerce',
    'X-Cart',
    'CS-Cart',
    'osCommerce',
    'Zen Cart',
    'CubeCart',
    'AbanteCart',
    'LiteCart',
    'TomatoCart',
    'OpenCart',
    'PrestaShop',
    'WooCommerce',
    'Shopware',
    'OroCommerce',
    'Broadleaf Commerce',
    'Virto Commerce',
    'nopCommerce',
    'X-Cart',
    'CS-Cart',
    'osCommerce',
    'Zen Cart',
    'CubeCart',
    'AbanteCart',
    'LiteCart',
    'TomatoCart',
    'OpenCart',
    'PrestaShop',
    'WooCommerce',
  ];

  return (
    <Container
      sx={{ mt: 2, display: 'flex', flexWrap: 'wrap', alignItems: 'center' }}
    >
      {Technologies.map((tech, index) => (
        <Link
          to={`/tags/${tech}`}
          key={index}
          style={{ textDecoration: 'none' }}
        >
          <Button variant="outlined" color="info" sx={{ m: 0.4 }}>
            {tech}
          </Button>
        </Link>
      ))}
    </Container>
  );
};

export default Tags;
